version: '1'
services:
  influxDB:
    image: influxdb:2.0.9
    ports:
      - '8086:8086'
    volumes:
      - ./influxDB_data/:/var/lib/influxdb
 #   environment:
 #     - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
 #     - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  
  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - '3000:3000'
    volumes:
      - ./grafana_data/:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxDB
