version: '1'
services:
  influxDB:
    image: influxdb:2.0.9
    ports:
      - '8086:8086'
    volumes:
      - ./influxDB_data/:/var/lib/influxdb
    env_file: .env 
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=NOC
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      - DOCKER_INFLUXDB_INIT_RETENTION=365d
  
  grafana:
    image: grafana/grafana-enterprise:latest
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - ./grafana_data/:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxDB
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}